#!/usr/bin/env python3
"""
Generate report.md from artifacts/latest/metrics.json.

CML (in GitHub Actions) will post this file as a PR comment via:
    cml comment create report.md
"""

import json
from pathlib import Path

METRICS_PATH = Path("artifacts/latest/metrics.json")
REPORT_PATH  = Path("report.md")


def fmt(v, precision: int = 4) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{precision}f}"
    return str(v)


def main():
    data = json.loads(METRICS_PATH.read_text())
    v = data.get("voice",  {})
    vis = data.get("vision", {})

    lines = [
        f"# MLOps Demo Report",
        f"",
        f"| Key | Value |",
        f"|-----|-------|",
        f"| run_id | `{data.get('run_id', '—')}` |",
        f"| git_sha | `{data.get('git_sha', '—')}` |",
        f"| created_at_utc | {data.get('created_at_utc', '—')} |",
        f"",
        f"## Voice Pipeline (openWakeWord)",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| wakeword | {fmt(v.get('wakeword'))} |",
        f"| mode | {fmt(v.get('mode'))} |",
        f"| threshold | {fmt(v.get('threshold'), 2)} |",
        f"| FAR | {fmt(v.get('far'), 4)} |",
        f"| FRR | {fmt(v.get('frr'), 4)} |",
        f"",
    ]

    curve_png = v.get("curve_png")
    if curve_png and Path(curve_png).exists():
        lines.append(f"![Voice ROC]({curve_png})")
        lines.append("")

    lines += [
        f"## Vision Pipeline (CIFAR-10)",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| dataset | {fmt(vis.get('dataset'))} |",
        f"| model | {fmt(vis.get('model'))} |",
        f"| accuracy | {fmt(vis.get('accuracy'), 4)} |",
        f"| loss | {fmt(vis.get('loss'), 4)} |",
        f"",
    ]

    confusion_png = vis.get("confusion_png")
    if confusion_png and Path(confusion_png).exists():
        lines.append(f"![Confusion Matrix]({confusion_png})")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by `scripts/gen_report.py`*")

    report = "\n".join(lines)
    REPORT_PATH.write_text(report)
    print(f"Report written → {REPORT_PATH}")


if __name__ == "__main__":
    main()
